### ISSUE TITLE
Self-referential relationship for Ticket

### ISSUE THREAD

**Issue by vstpnv** [magnezio/mg-incident#18]
![2018-04-24_00-38-52](https://user-images.githubusercontent.com/38452207/39143465-2e091bba-4758-11e8-9db9-e62c23921d92.png)

**Comment by vstpnv** [comment]
Deny delete child rows

**Comment by blohinn** [comment]
Maybe deny delete parent rows?
Look:

ticket_1
--ticket_1_child_1
--ticket_1_child_2

I can remove ticket_1_child's, but i can't remove ticket_1 because it has childrens, not?
